language: cpp
dist: trusty
sudo: false

env:
  - COMPILER=clang++-3.9        
  - COMPILER=clang++-4.0        
  - COMPILER=g++-7        
  - COMPILER=g++-6        
  - COMPILER=g++-4.9

addons:
  ssh_known_hosts: vanklompf.westeurope.cloudapp.azure.com
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-trusty-4.0
    packages:
    - g++-7
    - g++-6
    - g++-4.9
    - clang-3.9
    - clang-4.0
    - cmake
    - libboost-program-options-dev

script:
  - openssl aes-256-cbc -K $encrypted_063301a0ac23_key -iv $encrypted_063301a0ac23_iv -in test/azure.rsa.enc -out test/azure.rsa -d
  - chmod 600 test/azure.rsa
  - export CXX=$COMPILER
  - cmake . && make -j$(nproc) && make test && cd test && ./runPerformance.sh $TRAVIS_BUILD_NUMBER "$TRAVIS_COMMIT_MESSAGE" $COMPILER

notifications:
  email: false
