language: cpp
compiler:
  - clang
  - gcc
dist: trusty
sudo: false

before_install:
  - gcc --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - cmake
    - llvm 
    - libboost-program-options-dev

script:
  - export CXX=g++-6
  - $CXX --version
  - g++ --version
  - clang --version
  - cmake . && make
  - ./hashfun

notifications:
  email: false
