language: cpp
dist: trusty
sudo: false

env:
  - COMPILER=g++-6
  - COMPILER=g++-5

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - gcc-5
    - g++-5
    - cmake
    - clang-3.9
    - libboost-program-options-dev

script:
  - $CXX --version
  - g++ --version
  - clang --version
  - cmake . && make
  - ./hashfun

notifications:
  email: false
