language: cpp
dist: trusty
sudo: false

env:
  - COMPILER=clang++
  - COMPILER=g++-6
  - COMPILER=g++-5
  - COMPILER=g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - gcc-5
    - g++-5
    - cmake
    - clang-3.5
    - libboost-program-options-dev

script:
  - export CXX=$COMPILER
  - $CXX --version
  - cmake . && make
  - ./hashfun

notifications:
  email: false
