language: cpp
dist: trusty
sudo: false

env:
  - COMPILER=clang++-3.9
  - COMPILER=clang++-4.0
  - COMPILER=g++-6
  - COMPILER=g++-5
  - COMPILER=g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-4.0
    - llvm-toolchain-trusty-3.9
    packages:
    - g++-6
    - g++-5
    - cmake
    - clang-3.9
    - clang-4.0
    - libboost-program-options-dev
    - binutils-gold

script:
  - export CXX=$COMPILER
  - $CXX --version
  - cmake . && make
  - ./hashfun

notifications:
  email: false
