language: cpp
compiler: gcc
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - cmake

script:
  - export CXX=g++-6
  - cmake . && make

notifications:
  email: false
