language: cpp
dist: trusty
sudo: false

env:
  - COMPILER=g++-4.9

addons:
  ssh_known_hosts: vanklompf.westeurope.cloudapp.azure.com
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-trusty-4.0
    packages:
    - g++-4.9
    - cmake
    - libboost-program-options-dev

script:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in test/azure.rsa.enc -out test/azure.rsa -d
  - chmod 600 test/azure_ssh
  - export CXX=$COMPILER
  - cmake . && make -j$(nproc) && make test && cd test && ./runPerformance.sh $TRAVIS_BUILD_NUMBER $TRAVIS_COMMIT_MESSAGE $COMPILER

notifications:
  email: false
