language: cpp
dist: trusty
sudo: false

env:
  - COMPILER=clang++-3.5
  - COMPILER=clang++-4.0
  - COMPILER=g++-6
  - COMPILER=g++-5
  - COMPILER=g++
  - COMPILER=clang++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-trusty-4.0
    packages:
    - g++-6
    - g++-5
    - cmake
    - clang-3.5
    - clang-4.0
    - libboost-program-options-dev
    - binutils-gold
    - binutils-dev

script:
  - export CXX=$COMPILER
  - cmake . && make
  - ./hashfun

notifications:
  email: false
